[{
        StoreName: "承融藥局 ",
        Addres: "桃園市龍潭區中興路282號",
        phone: "03-4095543"
    },
    {
        StoreName: "弘安藥局  ",
        Addres: "桃園市楊梅區新農街15號",
        phone: "03-4782115"
    },
    {
        StoreName: "弘安育藥局 ",
        Addres: "桃園市龍潭區北龍路一四四號",
        phone: "03-4808824"
    },
    {
        StoreName: "維益特藥局 ",
        Addres: "桃園市八德區和平路190號",
        phone: "03-3677885"
    },
    {
        StoreName: "中美健保特約藥局 ",
        Addres: "桃園市楊梅區埔心里中興路77號",
        phone: "03-4822483"
    },
    {
        StoreName: "達安藥師藥局  ",
        Addres: "桃園市大有路646號",
        phone: "03-3583582"
    },
    {
        StoreName: "美康健保藥局 ",
        Addres: "桃園市桃園區中山東路82號",
        phone: "03-3394007"
    },
    {
        StoreName: "和信藥局  ",
        Addres: "桃園市龜山區南祥路58號1樓",
        phone: "03-2124028"
    },
    {
        StoreName: "康熙藥局 ",
        Addres: "桃園市龍潭區中正路128號",
        phone: "03-4801508"
    },
    {
        StoreName: "合康美藥局 ",
        Addres: "桃園市楊梅區中山北路二段79號",
        phone: "03-4812598"
    },
    {
        StoreName: "大興藥師藥局 ",
        Addres: "桃園市桃園區大德一街96號",
        phone: "03-3266868"
    },
    {
        StoreName: "民富大藥局 ",
        Addres: "桃園市桃園區大有路488號一樓",
        phone: "03-3469976"
    },
    {
        StoreName: "龍泰藥局   ",
        Addres: "桃園市楊梅區民族路五段147巷2號",
        phone: "03-4901525"
    },
    {
        StoreName: "晴一藥局  ",
        Addres: "桃園市中壢區民族路五段258號",
        phone: "03-4909427"
    },
    {
        StoreName: "星康生活藥局  ",
        Addres: "桃園市中壢區中美路二段94號",
        phone: "03-4252869"
    },
    {
        StoreName: "悅發藥局  ",
        Addres: "桃園市龍潭區龍元路86號",
        phone: "03-4794438"
    },
    {
        StoreName: "大榮藥妝  ",
        Addres: "桃園市龍潭區凌雲里中豐路上林段2號",
        phone: "03-4797795"
    },
    {
        StoreName: "上禾藥師藥局  ",
        Addres: "桃園市中壢區新生路215號",
        phone: "03-4269277"
    },
    {
        StoreName: "千葉大藥局  ",
        Addres: "桃園市中壢區新生路307號",
        phone: "03-4251886"
    },
    {
        StoreName: "大立健保藥局 ",
        Addres: "桃園市龍潭區民族路 192號1樓",
        phone: "03-4093487"
    },
    {
        StoreName: "閤家康聯合藥局 ",
        Addres: "桃園市平鎮區中豐路山頂段256號",
        phone: "03-4194550"
    },
    {
        StoreName: "懷仁藥師健保藥局  ",
        Addres: "桃園市中壢區中北路93號1樓",
        phone: "03-4378466"
    },
    {
        StoreName: "祥合藥局 ",
        Addres: "桃園市中壢區中北路二段431號",
        phone: "03-2841880"
    },
    {
        StoreName: "左外野藥局 ",
        Addres: "桃園市龜山區文光街6號1樓",
        phone: "03-3271503"
    },
    {
        StoreName: "南崁宜安藥師藥局 ",
        Addres: "桃園市蘆竹區南崁路248號",
        phone: "03-3220686"
    },
    {
        StoreName: "安利藥局",
        Addres: "桃園市中壢區龍東路504號",
        phone: "03-4562824"
    },
    {
        StoreName: "吉康生活藥局",
        Addres: "桃園市八德區義勇街120號",
        phone: "03-3768577"
    },
    {
        StoreName: "101藥師聯合藥局 ",
        Addres: "桃園市龍潭區中正路44號",
        phone: "03-4708593"
    },
    {
        StoreName: "瑞瑄藥局",
        Addres: "桃園市平鎮區中豐路南勢二段162號",
        phone: "03-4396205"
    },
    {
        StoreName: "華生藥師藥局",
        Addres: "桃園市楊梅區埔心里中興路89號",
        phone: "03-4821839"
    },
    {
        StoreName: "新象聯合藥局",
        Addres: "桃園市中壢區元化路62號",
        phone: "03-4277585"
    },
    {
        StoreName: "新賀生大藥局",
        Addres: "桃園市中壢區中山東路3段260號",
        phone: "03-4163900"
    },
    {
        StoreName: "奕成大藥局 ",
        Addres: "桃園市八德區興豐路673號1樓",
        phone: "03-3732113"
    },
    {
        StoreName: "百年聯和藥局",
        Addres: "桃園市龍潭區中豐路300號",
        phone: "03-4895268"
    },
    {
        StoreName: "欣康藥局",
        Addres: "桃園市大溪區員林路2段390－6號",
        phone: "03-3076310"
    },
    {
        StoreName: "鴻安中西藥局",
        Addres: "桃園市中壢區新中北路二段191號1F",
        phone: "03-452-0615"
    },
    {
        StoreName: "永崴大藥局",
        Addres: "桃園市中壢區莊敬路783號",
        phone: "03-4513537"
    },
    {
        StoreName: "新寶樹藥局",
        Addres: "桃園市八德區介壽路一段974號",
        phone: "03-3770000"
    },
    {
        StoreName: "博爾康生活藥局",
        Addres: "桃園市龜山區大同路250號1樓",
        phone: "03-3506588"
    },
    {
        StoreName: "美佑康活力藥局",
        Addres: "桃園市中壢區五福里中正路627號",
        phone: "03-2810018"
    },
    {
        StoreName: "壽德藥師藥局",
        Addres: "桃園市八德區桃德路84號",
        phone: "03-3666350"
    },
    {
        StoreName: "思琁藥師藥局",
        Addres: "桃園市中壢區中北路二段430號",
        phone: "03-4162189 "
    },
    {
        StoreName: "新華興健保藥局",
        Addres: "桃園市桃園區中山東路10號",
        phone: "03-3335977"
    },
    {
        StoreName: "樂謙藥師藥局",
        Addres: "桃園市中壢區龍東路134號",
        phone: "03-4662775"
    },
    {
        StoreName: "景賀藥局",
        Addres: "桃園市平鎮區金陵路三段66-6號",
        phone: "03-4570991"
    },
    {
        StoreName: "康橋藥局",
        Addres: "桃園市桃園區國際路一段1029號",
        phone: "03-2173588"
    },
    {
        StoreName: "莘莘藥局",
        Addres: "桃園市莊敬路一段368號",
        phone: "03-3170681-10"
    },
    {
        StoreName: "聖昌藥師藥局",
        Addres: "桃園市中正路1238號 ",
        phone: "03-3266654"
    },
    {
        StoreName: "華康中西藥局",
        Addres: "桃園市桃園區中埔六街3號",
        phone: "03-3166920"
    },
    {
        StoreName: "迦南藥局",
        Addres: "桃園市桃園區國聖一街61號1樓之1",
        phone: "03-360-9938"
    },
    {
        StoreName: "薰衣草藥局 ",
        Addres: "桃園市中壢區新生路335號",
        phone: "03-4253330"
    }
]