[{
        StoreName: "信昌藥局",
        phone: "08-7397337",
        Address: "屏東縣九如鄉九如路二段119號",
        map: "https://goo.gl/maps/AZjxKDFKBQkqyuYD9"
    },
    {
        StoreName: "弘英藥局",
        phone: "08-7366898",
        Address: "屏東縣屏東市中正路702-11號",
        map: "https://goo.gl/maps/fhKiwAnpbFKFCpQh9"
    },
    {
        StoreName: "友一藥局 ",
        phone: "037-467776",
        Address: "苗栗縣竹南鎮照南里一一鄰民族街一四六號",
        map: "https://goo.gl/maps/bRG9x4fvCstSmCW27"
    },
    {
        StoreName: "宗勳藥局",
        phone: "07-8034600",
        Address: "高雄市小港區康莊路60號",
        map: "https://goo.gl/maps/LaxCBnDnbpNHaPWt7"
    },
    {
        StoreName: "康威藥局",
        phone: "07-3223189",
        Address: "高雄市三民區九如二路301號",
        map: "https://goo.gl/maps/xV9nP2RNZt5nHryX7"
    },
    {
        StoreName: "好好藥局",
        phone: "03-5366996",
        Address: "新竹市北區中福路83號",
        map: "https://goo.gl/maps/ErzU7XJ77V3SDere8"
    },
    {
        StoreName: "康博中西藥局",
        phone: "03-5191010",
        Address: "新竹市東區明湖里明湖路446之4號",
        map: "https://goo.gl/maps/xkpzVHNyn5DBXn1E6"
    },
    {
        StoreName: "中和西藥房",
        phone: "03-5241602",
        Address: "新竹市城北街56號",
        map: "https://goo.gl/maps/7Ej43zcC64kocg1A8"
    },
    {
        StoreName: "大庄藥局",
        phone: "03-5309901",
        Address: "新竹市香山區香山里大庄路110號",
        map: "https://goo.gl/maps/tEYy4ChRivTMQBkh6"
    },
    {
        StoreName: "台安藥局",
        phone: "03-5245838",
        Address: "新竹市北大路298號",
        map: "https://goo.gl/maps/DVpmmJwxwkhWHXTVA"
    }
]